'use strict';
const $=s=>document.querySelector(s), KEY='paisa-v1', types={expense:'Expense',opening:'Opening balance',income:'Income',borrow:'Borrowed',lend:'Lent','debt-opening':'Existing debt','loan-opening':'Existing loan',repay:'Repaid',collect:'Collected',transfer:'Transfer',invest:'Investment','investment-opening':'Existing investment'};
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money=p=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(p/100);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const investmentCategories=['Share market','Gold','SIP','Bhisi'];
const personKey=s=>s.trim().toLocaleLowerCase('en-IN');
let state={version:1,entries:[],reminder:{time:'21:00',enabled:false}}, damaged=false;
function notify(s,error=false){$('#notice').hidden=false;$('#notice').textContent=s;$('#notice').className=error?'error':'';}
function validate(data){
 if(!data||data.version!==1||!Array.isArray(data.entries)||data.entries.length>50000)throw Error('This is not a valid Paisa backup.');
 const ids=new Set(); for(const e of data.entries){if(typeof e.id!=='string'||ids.has(e.id)||!Object.hasOwn(types,e.type)||!Number.isSafeInteger(e.amount)||e.amount<=0||e.amount>99999999900||!['Bank','Cash'].includes(e.account)||typeof e.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||Number.isNaN(Date.parse(e.date))||new Date(e.date).toISOString().slice(0,10)!==e.date||typeof e.note!=='string'||e.note.length>160||typeof e.person!=='string'||e.person.length>60||typeof e.category!=='string'||e.category.length>80||typeof e.purpose!=='string')throw Error('Invalid entry in backup. No data was changed.'); if(e.type==='expense'&&!['Useful','Unnecessary'].includes(e.purpose))throw Error('Invalid expense label.'); if(['borrow','lend','debt-opening','loan-opening','repay','collect'].includes(e.type)&&!e.person.trim())throw Error('Udhari entries need a person.');if(['invest','investment-opening'].includes(e.type)&&!investmentCategories.includes(e.category))throw Error('Invalid investment category.');ids.add(e.id);}
 if(!data.reminder||!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.reminder.time)||typeof data.reminder.enabled!=='boolean')throw Error('Invalid reminder settings.');
 const totals=calculate(data.entries); if(Object.values(totals.people).some(p=>p.owe<0||p.receive<0))throw Error('Repayments exceed recorded udhari. Correct the related entries first.'); return data;
}
try{const saved=localStorage.getItem(KEY);if(saved)state=validate(JSON.parse(saved));}catch(e){damaged=true;notify('Saved data could not be read. It has not been overwritten. Restore a valid backup to continue.',true);}
function commit(next){try{validate(next);localStorage.setItem(KEY,JSON.stringify(next));state=next;render();return true;}catch(e){notify(e.message||'Could not save. Download a backup and check browser storage.',true);return false;}}
function calculate(entries=state.entries){let bank=0,cash=0,investments=Object.fromEntries(investmentCategories.map(c=>[c,0])),people=Object.create(null);for(const e of entries){if(['invest','investment-opening'].includes(e.type))investments[e.category]=(investments[e.category]||0)+e.amount;let delta=0;if(['opening','income','borrow','collect'].includes(e.type))delta=e.amount;if(['expense','lend','repay','invest'].includes(e.type))delta=-e.amount;if(e.type==='transfer'){if(e.account==='Bank'){bank-=e.amount;cash+=e.amount;}else{cash-=e.amount;bank+=e.amount;}}else if(e.account==='Bank')bank+=delta;else cash+=delta;
 if(['borrow','lend','debt-opening','loan-opening','repay','collect'].includes(e.type)){const k=personKey(e.person);const p=people[k]??={name:e.person.trim(),owe:0,receive:0};if(['borrow','debt-opening'].includes(e.type))p.owe+=e.amount;if(e.type==='repay')p.owe-=e.amount;if(['lend','loan-opening'].includes(e.type))p.receive+=e.amount;if(e.type==='collect')p.receive-=e.amount;}}
 const owe=Object.values(people).reduce((a,p)=>a+p.owe,0),receive=Object.values(people).reduce((a,p)=>a+p.receive,0);const invested=Object.values(investments).reduce((a,n)=>a+n,0);return{bank,cash,available:bank+cash,invested,investments,savings:bank+cash+invested,owe,receive,net:bank+cash+invested+receive-owe,people};}
function expenses(month){const rows=state.entries.filter(e=>e.type==='expense'&&e.date.startsWith(month));const total=rows.reduce((a,e)=>a+e.amount,0),useful=rows.filter(e=>e.purpose==='Useful').reduce((a,e)=>a+e.amount,0);return{rows,total,useful,unnecessary:total-useful};}
function render(){const c=calculate(),m=expenses(localDate().slice(0,7)),v=expenses($('#month').value);for(const k of ['available','owe','receive','bank','cash','net','invested'])$('#'+k).textContent=money(c[k]);$('#spent').textContent=money(m.total);$('#spent-note').textContent=`${m.rows.length} expense${m.rows.length===1?'':'s'} recorded`;$('#useful').textContent=money(v.useful);$('#unnecessary').textContent=money(v.unnecessary);$('#useful-bar').style.width=v.total?`${v.useful/v.total*100}%`:'0%';$('.spend-bar').style.background=v.total?'var(--orange)':'#eaf0ed';$('#insight').textContent=v.total?`${Math.round(v.useful/v.total*100)}% of spending in the selected month was marked useful by you.`:'Add your first expense to see your spending split.';
 $('#savings-cash').textContent=money(c.cash);$('#savings-bank').textContent=money(c.bank);$('#savings-invested').textContent=money(c.invested);$('#savings-total').textContent=money(c.savings);
 const alerts=Object.values(c.people).filter(p=>p.receive>700000).sort((a,b)=>b.receive-a.receive);$('#udhari-alert').hidden=!alerts.length;$('#udhari-alert').innerHTML='<h2>Udhari above ₹7,000</h2>'+alerts.map(p=>`<div class="split-line"><span>${esc(p.name)} owes you</span><strong>${money(p.receive)}</strong></div>`).join('');
 $('#investment-breakdown').innerHTML=Object.entries(c.investments).map(([name,amount])=>`<div class="split-line"><span>${esc(name)}</span><strong>${money(amount)}</strong></div>`).join('');
 const investmentRows=state.entries.filter(e=>['invest','investment-opening'].includes(e.type)).slice().sort((a,b)=>b.date.localeCompare(a.date));$('#investment-entries').innerHTML=investmentRows.map(e=>`<div class="entry"><div class="entry-info"><strong>${esc(e.note||e.category)}</strong><small>${esc(e.date)} · ${esc(e.category)} · ${e.type==='investment-opening'?'Existing investment · no cash change':esc(e.account==='Bank'?'Bank / online':e.account)}</small></div><div class="entry-end"><strong>${money(e.amount)}</strong></div></div>`).join('')||'<p class="empty">No investments recorded yet.</p>';
 const cats=Object.create(null);v.rows.forEach(e=>cats[e.category]=(cats[e.category]||0)+e.amount);$('#categories').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="split-line"><span>${esc(k)}</span><strong>${money(v)}</strong></div>`).join('');
 const rows=state.entries.filter(e=>e.date.startsWith($('#month').value)).map((e,i)=>({...e,order:i})).sort((a,b)=>b.date.localeCompare(a.date)||b.order-a.order);
 $('#entries').innerHTML=rows.length?rows.map(e=>`<div class="entry"><div class="entry-icon">${e.type==='expense'?'−':'₹'}</div><div class="entry-info"><strong>${esc(e.note||types[e.type])}</strong><small>${esc(e.date)} · ${esc(e.type==='expense'?e.category:types[e.type])} · ${esc(e.account)}${e.person?' · '+esc(e.person):''}</small>${e.type==='expense'?`<br><span class="badge ${e.purpose==='Unnecessary'?'unnecessary':''}">${esc(e.purpose)}</span>`:''}</div><div class="entry-end"><strong>${money(e.amount)}</strong><div class="entry-actions">${e.type==='expense'?`<button data-edit="${esc(e.id)}">Edit</button>`:''}<button data-delete="${esc(e.id)}" aria-label="Delete ${esc(e.note||types[e.type])}">Delete</button></div></div></div>`).join(''):'<div class="empty">No entries this month.<br>Add your starting balance, then your first expense.</div>';
 $('#debts').innerHTML=Object.values(c.people).filter(p=>p.owe||p.receive).map(p=>`<div class="split-line"><span>${esc(p.name)}</span><span>${p.owe?`I owe <strong>${money(p.owe)}</strong><br>`:''}${p.receive?`To receive <strong>${money(p.receive)}</strong>`:''}</span></div>`).join('')||'<p class="muted">No outstanding udhari.</p>';
 $('#people').innerHTML=Object.values(c.people).map(p=>`<option value="${esc(p.name)}">`).join('');$('#reminder-time').value=state.reminder.time;$('#reminder-enabled').checked=state.reminder.enabled;$('#reminder-summary').textContent=`Page reminder: ${state.reminder.enabled?'on at '+state.reminder.time:'off'}. Calendar reminders are managed separately in your calendar app.`;}
function tab(id){document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===id));}
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>tab(e.dataset.tab));document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>tab(e.dataset.go));
function parseAmount(s){if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('Enter a positive amount with up to two decimal places.');return Math.round(Number(s)*100);}
function add(form,type){if(damaged){notify('Restore a valid backup before adding entries.',true);return;}try{const f=new FormData(form);const e={id:crypto.randomUUID(),type,amount:parseAmount(f.get('amount')),date:f.get('date'),account:f.get('account'),note:(f.get('note')||'').trim(),person:(f.get('person')||'').trim(),category:f.get('category')||'',purpose:f.get('purpose')||''};if(e.date>localDate())throw Error('Use today or an earlier date for actual transactions.');if(type==='opening'&&state.entries.some(x=>x.type==='opening'&&x.account===e.account))throw Error('This account already has an opening balance. Delete the old opening entry to correct it, or use Income for new money.');
 if(commit({...state,entries:[...state.entries,e]})){form.reset();form.elements.date.value=localDate();typeHelp();notify('Entry saved on this device.');}}catch(e){notify(e.message,true);}}
$('#expense-form').onsubmit=e=>{e.preventDefault();add(e.target,'expense');};$('#money-form').onsubmit=e=>{e.preventDefault();add(e.target,$('#money-type').value);};
$('#investment-form').onsubmit=e=>{e.preventDefault();add(e.target,$('#investment-type').value);investmentHelp();};
function investmentHelp(){$('#investment-help').textContent=$('#investment-type').value==='investment-opening'?'Existing investments do not change your current bank or cash balance.':'New investments reduce the selected cash or bank balance. They are not counted as expenses.';}
$('#investment-type').onchange=investmentHelp;
function typeHelp(){const t=$('#money-type').value;$('#money-form').elements.person.required=['borrow','lend','debt-opening','loan-opening','repay','collect'].includes(t);$('#type-help').textContent=t==='transfer'?'Moves money to the other account. Total available money stays the same.':t==='debt-opening'||t==='loan-opening'?'Records older udhari without changing your current cash or bank balance.':t==='repay'||t==='collect'?'Enter the same person used for the original loan. Repayment cannot exceed their outstanding amount.':t==='opening'?'Add one opening balance per account. Do not record old spending already included in this balance.':'';}
$('#money-type').onchange=typeHelp;$('#month').onchange=render;
$('#entries').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.delete||b.dataset.edit,entry=state.entries.find(x=>x.id===id);if(b.dataset.delete){if(confirm('Delete this entry? All balances will be recalculated.')){if(commit({...state,entries:state.entries.filter(x=>x.id!==id)}))notify('Entry deleted.');}}else{const f=$('#edit-form');for(const k of ['id','date','note','purpose'])f.elements[k].value=entry[k];f.elements.amount.value=(entry.amount/100).toFixed(2);$('#edit-dialog').showModal();}};
$('#cancel-edit').onclick=()=>$('#edit-dialog').close();$('#edit-form').onsubmit=e=>{e.preventDefault();try{const f=e.target.elements;if(f.date.value>localDate())throw Error('Use today or an earlier date.');if(commit({...state,entries:state.entries.map(x=>x.id===f.id.value?{...x,amount:parseAmount(f.amount.value),date:f.date.value,note:f.note.value.trim(),purpose:f.purpose.value}:x)})){$('#edit-dialog').close();notify('Expense updated.');}}catch(err){notify(err.message,true);}};
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('#backup').onclick=()=>download(damaged?(localStorage.getItem(KEY)||'{}'):JSON.stringify(state,null,2),`paisa-backup-${localDate()}.json`,'application/json');
$('#restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>30000000)throw Error('Backup is too large.');const next=validate(JSON.parse(await file.text()));if(confirm(`Replace all current data with ${next.entries.length} entries from this backup? Download a backup first if needed.`)){if(commit(next)){damaged=false;notify('Backup restored.');}}}catch(err){notify(err.message,true);}e.target.value='';};
$('#export').onclick=()=>{if(damaged){notify('Restore valid data before exporting Excel.',true);return;}const c=calculate(),m=expenses(localDate().slice(0,7));exportExcel([{name:'Summary',rows:[['PAISA • PERSONAL EXPENSES','INR'],['Export date',localDate()],['Available money',c.available/100],['Bank / online',c.bank/100],['Cash',c.cash/100],['Invested capital',c.invested/100],['Available + invested',c.savings/100],['Udhari - I owe',c.owe/100],['Udhari - to receive',c.receive/100],['Net position',c.net/100],['Current month',localDate().slice(0,7)],['Spent this month',m.total/100],['Useful this month',m.useful/100],['Unnecessary this month',m.unnecessary/100],['Note','Exported snapshot. All entries are included on the Entries sheet.']]},{name:'Entries',rows:[['Date','Type','Amount (INR)','Account','Category','Purpose','Person','Note','ID'],...state.entries.map(e=>[e.date,types[e.type],e.amount/100,e.account,e.category,e.purpose,e.person,e.note,e.id])]},{name:'Investments',rows:[['Category','Invested capital (INR)'],...Object.entries(c.investments).map(([k,v])=>[k,v/100]),['Total invested capital',c.invested/100],['Valuation','Recorded contributions only; no market prices or profit/loss']]},{name:'Udhari',rows:[['Person','I owe (INR)','To receive (INR)'],...Object.values(c.people).map(p=>[p.name,p.owe/100,p.receive/100])]}],`Paisa-${localDate()}.xlsx`);notify('Excel export downloaded. Keep a JSON backup for restoring into the app.');};
$('#reminder-form').onsubmit=e=>{e.preventDefault();if(damaged)return notify('Restore a backup first.',true);if(commit({...state,reminder:{time:$('#reminder-time').value,enabled:$('#reminder-enabled').checked}}))notify('Page reminder saved. Use a calendar reminder or Clock alarm when the page is closed.');};
$('#calendar').onclick=()=>{const time=$('#reminder-time').value;if(!time)return;const [h,m]=time.split(':').map(Number);const next=new Date();next.setHours(h,m,0,0);if(next<=new Date())next.setDate(next.getDate()+1);const stamp=next.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const local=localDate(next).replace(/-/g,'')+'T'+time.replace(':','')+'00';const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Paisa//Daily Expense Reminder//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:'+crypto.randomUUID()+'@paisa.local','DTSTAMP:'+stamp,'DTSTART:'+local,'DURATION:PT10M','RRULE:FREQ=DAILY','SUMMARY:Fill Paisa expense tracker','DESCRIPTION:Open your Paisa tracker and record today\'s expenses.','BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:Time to record your daily expenses','END:VALARM','END:VEVENT','END:VCALENDAR'];download(lines.join('\r\n')+'\r\n','Paisa-daily-reminder.ics','text/calendar');notify('Calendar file downloaded. Import it into your calendar and verify the reminder is enabled. Re-importing can create duplicates.');};
let fired='';function checkReminder(){if(!state.reminder.enabled||document.visibilityState!=='visible')return;const now=new Date(),time=now.toTimeString().slice(0,5),key=localDate()+' '+state.reminder.time;if(time===state.reminder.time&&fired!==key){fired=key;notify('Time to record today’s expenses.');tab('overview');$('#expense-form').elements.amount.focus();}}
setInterval(checkReminder,15000);document.addEventListener('visibilitychange',checkReminder);
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
window.addEventListener('storage',e=>{if(e.key===KEY){try{if(e.newValue){state=validate(JSON.parse(e.newValue));render();notify('Updated from another tab.');}else{damaged=true;notify('Data was cleared in another tab. Reload before continuing.',true);}}catch{damaged=true;notify('Another tab saved invalid data. Restore a backup.',true);}}});
$('#month').value=localDate().slice(0,7);document.querySelectorAll('input[type=date]').forEach(e=>{e.value=localDate();e.max=localDate();});$('#today').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase();render();typeHelp();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>notify('Offline mode is unavailable. Online tracking still works.',true));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_expense_summary',description:'Read current balances and this month’s spending.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No parameters expected.');return{currency:'INR',unit:'paise',...calculate(),month:localDate().slice(0,7),spending:expenses(localDate().slice(0,7)).total};}})).catch(()=>{});}catch{}}
